### ISSUE TITLE
[WebSocket] Exception Unexpected character encountered while parsing value: M. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by codemaker2015** [ethereum-boilerplate/web3-unity-boilerplate#93] opened 2022-04-12 07:52 UTC
I am not able to sign in to the web3 wallet on an Android device. Getting a parsing exception for running the code on Android target devices. After checking the logs I understood that there are some WebSocket exceptions are throwing while connecting the web3 wallet on Android devices. 

`[WebSocket] Exception Unexpected character encountered while parsing value: M. Path '', line 0, position 0.`

**Comment by schwindy** [comment] 2022-04-14 18:14
@codemaker2015  I have found that notice to not matter. That notice shows even when things are "working" ha...

I do wish that notice was hidden or shown less, though.

**Comment by KoenRijpstra** [comment] 2022-04-29 13:46
It looks like this message is coming from the WebSocket KeepAlive function trying to ping the WalletConnect bridge. The WalletConnect bridge then response with "Missing or invalid socket data": https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/servers/relay/src/ws.ts#L98. Going to talk to WalletConnect team and see if this is by design or not.

**Comment by KoenRijpstra** [comment] 2022-05-20 15:36
Fixed in the new 1.2.0 release 🥳

**Closed by KoenRijpstra** 2022-05-20 15:36 UTC
